"""Add approval status to price list

Revision ID: 6367d9fa941b
Revises: 88622d29f49b
Create Date: 2026-07-01 15:49:11.051124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6367d9fa941b'
down_revision = '88622d29f49b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_list_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_status', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_list_items', schema=None) as batch_op:
        batch_op.drop_column('approval_status')

    # ### end Alembic commands ###
