"""Simplify price list to one approved price per service

Revision ID: 88622d29f49b
Revises: d52c2c05c90f
Create Date: 2026-07-01 15:16:39.122788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88622d29f49b'
down_revision = 'd52c2c05c90f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_list_items', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_institution_service_price', ['institution_id', 'service_name'])
        batch_op.drop_column('service_category')
        batch_op.drop_column('effective_to')
        batch_op.drop_column('discount')
        batch_op.drop_column('effective_from')
        batch_op.drop_column('cash_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_list_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cash_price', sa.NUMERIC(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('effective_from', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('discount', sa.NUMERIC(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('effective_to', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('service_category', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint('uq_institution_service_price', type_='unique')

    # ### end Alembic commands ###
