"""Add price list batch workflow

Revision ID: 8ed890f85efe
Revises: 6367d9fa941b
Create Date: 2026-07-01 16:15:18.014387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ed890f85efe'
down_revision = '6367d9fa941b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_list_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_institution_service_price'), type_='unique')
        batch_op.create_index(batch_op.f('ix_price_list_items_batch_id'), ['batch_id'], unique=False)
        batch_op.create_unique_constraint('uq_batch_service_price', ['batch_id', 'service_name'])
        batch_op.create_foreign_key(
            'fk_price_list_items_batch_id',
            'price_list_batches',
            ['batch_id'],
            ['id']
        )
        batch_op.drop_column('approval_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_list_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_status', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint('uq_batch_service_price', type_='unique')
        batch_op.drop_index(batch_op.f('ix_price_list_items_batch_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_institution_service_price'), ['institution_id', 'service_name'])
        batch_op.drop_column('batch_id')

    # ### end Alembic commands ###
