"""Update price list item pricing fields

Revision ID: d52c2c05c90f
Revises: ea2d78f845bd
Create Date: 2026-06-29 15:49:23.302127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd52c2c05c90f'
down_revision = 'ea2d78f845bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_list_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cash_price', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_list_items', schema=None) as batch_op:
        batch_op.drop_column('discount')
        batch_op.drop_column('cash_price')

    # ### end Alembic commands ###
