"""Add medical claim models

Revision ID: dfe4070b0107
Revises: 8ed890f85efe
Create Date: 2026-07-02 15:33:53.857686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfe4070b0107'
down_revision = '8ed890f85efe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_claims',
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=200), nullable=False),
    sa.Column('receipt_file_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medical_claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_claims_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_claims_institution_id'), ['institution_id'], unique=False)

    op.create_table('medical_claim_items',
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('receipt_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('approved_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('difference', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('validation_status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['medical_claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medical_claim_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_claim_items_claim_id'), ['claim_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_claim_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_claim_items_claim_id'))

    op.drop_table('medical_claim_items')
    with op.batch_alter_table('medical_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_claims_institution_id'))
        batch_op.drop_index(batch_op.f('ix_medical_claims_employee_id'))

    op.drop_table('medical_claims')
    # ### end Alembic commands ###
